name: test_eccomarce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
    # --- Core & Utilities ---
  async: ^2.13.0
  equatable: ^2.0.8
  get_it: ^9.2.0
  shared_preferences: ^2.5.4


  # --- UI & Animations ---
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  animate_do: ^4.2.0
  skeletonizer: ^2.1.2
  toastification: ^3.0.3

  # --- State Management & Routing ---
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
    # --- Localization ---
  easy_localization: ^3.0.8

  # --- Networking ---
  dio: ^5.9.1

  # --- Local Database ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # --- Internet Connection ---
  internet_connection_checker_plus: ^2.9.1+2
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800